version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: userAdmin
      POSTGRES_PASSWORD: userAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  msPagamento:
    build: .
    ports:
      - "8084:8084"
    environment:
      PORT: 8084
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: userAdmin
      SPRING_DATASOURCE_PASSWORD: userAdmin
    depends_on:
      - db

volumes:
  postgres_data: